name: Dhall
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dhall-lang/setup-dhall@v4
      - run: dhall hash --file ./package.dhall
      - run: dhall-to-yaml --file ./example/config.dhall
      - run: dhall-to-yaml --file ./example/demo-node.dhall
      - run: echo "(./package.dhall).Utils.getIndexNamesList ./example/demo-node.dhall" | dhall text
