name: Haskell
on:
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    name: Haskell GHC
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - uses: haskell/actions/setup@v1
      with:
        ghc-version: "8.10"
    - uses: actions/cache@v2
      with:
        path: |
          ~/.cabal
          haskell/dist-newstyle
        key: ${{ runner.os }}-${{ matrix.ghc }}-${{ hashFiles('**/*.cabal','**/cabal.project') }}
        restore-keys: |
          ${{ runner.os }}-8.10-
          ${{ runner.os }}-
    - run: cabal update
    - run: cd haskell; cabal build --enable-tests --flags=ci all

    - name: Configure sysctl limits
      run: |
        sudo swapoff -a
        sudo sysctl -w vm.swappiness=1
        sudo sysctl -w fs.file-max=262144
        sudo sysctl -w vm.max_map_count=262144

    - name: Runs Elasticsearch
      uses: elastic/elastic-github-actions/elasticsearch@master
      with:
        stack-version: 7.8.0

    - name: Display indexes
      run: curl -s -I -X GET http://localhost:9200/_cat/indices

    - run: cd haskell; env ELASTIC_URL=http://localhost:9200 cabal test --enable-tests --flags=ci --test-show-details=direct
#    - run: cd haskell; cabal haddock
#    - run: cd haskell; cabal sdist
#    - run: cd haskell; cabal check
#    - run: cd haskell; cabal install --installdir=/tmp --overwrite-policy=always'}}
